//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsClient.ServiceReferenceBD {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceBD.IServiceData")]
    public interface IServiceData {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceData/AddStudent", ReplyAction="http://tempuri.org/IServiceData/AddStudentResponse")]
        void AddStudent(int id, string name, System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceData/AddStudent", ReplyAction="http://tempuri.org/IServiceData/AddStudentResponse")]
        System.Threading.Tasks.Task AddStudentAsync(int id, string name, System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceData/AddNumber", ReplyAction="http://tempuri.org/IServiceData/AddNumberResponse")]
        int AddNumber(int first, int second);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceData/AddNumber", ReplyAction="http://tempuri.org/IServiceData/AddNumberResponse")]
        System.Threading.Tasks.Task<int> AddNumberAsync(int first, int second);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceData/GetStudents", ReplyAction="http://tempuri.org/IServiceData/GetStudentsResponse")]
        WebService.Student[] GetStudents();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceData/GetStudents", ReplyAction="http://tempuri.org/IServiceData/GetStudentsResponse")]
        System.Threading.Tasks.Task<WebService.Student[]> GetStudentsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceData/DeleteStudent", ReplyAction="http://tempuri.org/IServiceData/DeleteStudentResponse")]
        void DeleteStudent(WebService.Student stud);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceData/DeleteStudent", ReplyAction="http://tempuri.org/IServiceData/DeleteStudentResponse")]
        System.Threading.Tasks.Task DeleteStudentAsync(WebService.Student stud);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceDataChannel : WindowsClient.ServiceReferenceBD.IServiceData, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceDataClient : System.ServiceModel.ClientBase<WindowsClient.ServiceReferenceBD.IServiceData>, WindowsClient.ServiceReferenceBD.IServiceData {
        
        public ServiceDataClient() {
        }
        
        public ServiceDataClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceDataClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceDataClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceDataClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AddStudent(int id, string name, System.DateTime date) {
            base.Channel.AddStudent(id, name, date);
        }
        
        public System.Threading.Tasks.Task AddStudentAsync(int id, string name, System.DateTime date) {
            return base.Channel.AddStudentAsync(id, name, date);
        }
        
        public int AddNumber(int first, int second) {
            return base.Channel.AddNumber(first, second);
        }
        
        public System.Threading.Tasks.Task<int> AddNumberAsync(int first, int second) {
            return base.Channel.AddNumberAsync(first, second);
        }
        
        public WebService.Student[] GetStudents() {
            return base.Channel.GetStudents();
        }
        
        public System.Threading.Tasks.Task<WebService.Student[]> GetStudentsAsync() {
            return base.Channel.GetStudentsAsync();
        }
        
        public void DeleteStudent(WebService.Student stud) {
            base.Channel.DeleteStudent(stud);
        }
        
        public System.Threading.Tasks.Task DeleteStudentAsync(WebService.Student stud) {
            return base.Channel.DeleteStudentAsync(stud);
        }
    }
}
